#!/bin/zsh
set -eux -o pipefail

# (re)install, idempotent
# run as user, not as root (no sudo)

base=${0:a:h}
cd $base

sudo apt install -y fzf
if ! dpkg --compare-versions $(fzf --version) ge 0.20.0; then
    echo 'your fzf version is older than 0.20.0' >&2
    exit 1
fi

(
    virtualenv --python python3.9 $base/.venv
    path=($base/.venv/bin $path)
    pip install --upgrade pip pip-tools
    pip-sync
)

systemd/install
