#!/bin/zsh
set -eux -o pipefail

# (re)install, idempotent
# run as user, not as root (no sudo)

base=${0:a:h}
cd $base

sudo apt install -y fzf
if ! dpkg --compare-versions $(fzf --version | cut -d ' ' -f 1) ge 0.20.0; then
    echo 'The fzf version appears to be older than 0.20.0.' >&2
    exit 1
fi

(
    cd $base
    if [[ ! -d .venv ]]; then
        virtualenv --python python3.9 .venv
    fi
    path=($base/.venv/bin $path)
    pip install --upgrade pip pip-tools
    pip-sync
)

systemd/install
