#!/bin/zsh
set -eux -o pipefail

# (re)install, idempotent
# run as user, not as root (no sudo)

base=${0:a:h}
cd $base

(
    virtualenv --python python3.9 $base/.venv
    path=($base/.venv/bin $path)
    pip install --upgrade pip pip-tools
    pip-sync
)

systemd/install
