#!/bin/zsh
#set -eux -o pipefail

autoload -U add-zsh-hook

function run {
    (
        source .venv/bin/activate
        export PYTHONPATH=python
        python $@
    )
}

function before {
    local command=${1[0,-2]}
    if [[ $command != '' ]]; then
        osh_current_command=(
            $(date +%s)  # start time
            $command  # command
        )
    fi
}

function after {
    local exit_code=$?
    if [[ -v osh_current_command ]]; then
        osh_current_command+=(
            $(date +%s)  # end time
            $exit_code  # exit code
            $(pwd)  # folder
            $(hostname)  # machine
        )
        run -m osh.socket insert-event $osh_current_command &!
        unset osh_current_command
    fi
}

add-zsh-hook zshaddhistory before
add-zsh-hook precmd after

#function osh-search {
#  local selected num
#  setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
#  selected=( $(fc -rl 1 | perl -ne 'print if !$seen{(/^\s*[0-9]+\s+(.*)/, $1)}++' |
#    FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS --query=${(qqq)LBUFFER} +m" $(__fzfcmd)) )
#  local ret=$?
#  if [ -n "$selected" ]; then
#    num=$selected[1]
#    if [ -n "$num" ]; then
#      zle vi-fetch-history -n $num
#    fi
#  fi
#  zle reset-prompt
#  return $ret
#}

function osh-search {
    BUFFER=$(run -m osh.socket fzf-select)
    CURSOR=$#BUFFER
}

zle -N osh-search
bindkey '^e' osh-search
