#!/usr/bin/env zsh
set -eu -o pipefail

# TODO do we need to mark them for export again?
# input env vars
# mode: -, all, session, folder, bag
#   "-" will show mode selection
# query: initial query
# session
# session_start  TODO is that needed here?
# folder
# TODO ah and also need to make sure that they are in fact set!

[[ $# == 0 ]]

# export query=${2:-}  # TODO query is not carried over when switching modes, escaping is a bit difficult
# but fzf probably can give it with one of {q} or so? does fzf have a solution for escaping there?

style=(
    --height=70%
    --min-height=10
    --info=inline-right
    --highlight-line
    --preview-window=down:10:wrap
    # NOTE --no-clear could be interesting, but flickering is not so bad now
)

if [[ $mode == - ]]; then
    args=(
        --delimiter=' '
        --with-nth=1
        --preview='print -- {2..}'
    )
    (
        print -- 'all search in all of history, forever, always.'
        print -- 'session search in the current session only'
        print -- 'folder search in the current folder only'
        print -- 'bag search an aggregated view of all unique commands in all of history, forever, always.'
    ) | fzf $style $args --bind='enter:become:mode={1} osh-fzf'
fi

args=(
    --prompt="$mode> "
    --query=$query
    --tiebreak=index
    --scheme=history
    --read0
    --delimiter=\\x1f
    --with-nth=3..
    --nth=2..
    --preview='echo {2} | base64 --decode'
    --print0
    --print-query
    --bind 'start:reload:osh search --mode=$mode --session=$session --folder=$folder'
    --bind 'enter:become:echo {1} | base64 --decode'
    --bind 'tab:become:mode=- osh-fzf'
)
fzf $style $args
