#!/bin/zsh
set -eux -o pipefail

# install into systemd, idempotent
# for the current user (dont run with sudo)

if [[ $USER == 'root' ]]; then
    echo 'not meant to be installed as a service for user root'
    exit 1
fi

export base=${0:a:h}
cat $base/one-shell-history@.service \
    | envsubst \
    | sudo tee /etc/systemd/system/one-shell-history@$USER.service

sudo systemctl daemon-reload
sudo systemctl enable one-shell-history@$USER.service
if ! sudo systemctl restart one-shell-history@$USER.service; then
    sudo systemctl status --no-pager --full one-shell-history@$USER.service
fi
