#!/bin/zsh
set -eux -o pipefail

# Install osh as a service in systemd.
# It's installed as a user service unit in
#   ~/.config/systemd
# and only run when the user is logged in.
# It's not constantly running in the background.
# It's not run as root, but only as your user.
# The installation is idempotent.
# Installation doesn't require sudo, dont run as root.

if [[ $USER == root ]]; then
    echo 'Dont install osh using sudo or as root.' >&2
    exit 1
fi

export base=${0:a:h}

cat $base/osh.service \
    | envsubst \
    | tee ~/.config/systemd/user/osh.service

systemctl --user daemon-reload
systemctl --user enable osh.service
systemctl --user restart osh.service || true
systemctl --user status --no-pager --full osh.service
